on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.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 }}
        uses: nikitasavinov/checkstyle-action@master
        with:
          reporter: 'github-pr-review'
          tool_name: 'testtool'
          level: error