name: reviewdog
on: [pull_request]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.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 }}
          reporter: github-pr-review
          level: warning