on: pull_request

jobs:
  checkstyle_job:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.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 }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'